name: revelio
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - seaborn
  - sqlalchemy
  - joblib
  - nltk
  - matplotlib
  - pyarrow
  - pip
  - statsmodels
  - graphviz
  - mlxtend
  - ipython
  - duckdb
  - pip:
      - doubleml
